#!/usr/bin/perl
use 5.010;
use strict;
use warnings;
use FindBin;                 
use lib "$FindBin::Bin/../lib";
use YAML_loader;
use Test::More tests => 3;

BEGIN {
	use_ok('YAML_loader');
}


subtest 'testa se subs existem no módulo' => sub {
	can_ok('YAML_loader','new');
	can_ok('YAML_loader','get_category');
};


subtest 'testa se objeto criado é uma instância da classe YAML_loader' => sub{
	my $yl=YAML_loader->new("../resources/yaml_files/taxonomia.yaml");
	isa_ok($yl,'YAML_loader');
};

1;


